-- Migration 028: stop anonymous LISTING of the storage buckets.
--
-- ═══════════════════════════════════════════════════════════════════════════
-- 🛑 DO NOT APPLY. THIS EXACT CHANGE ALREADY CAUSED A PRODUCTION OUTAGE.
-- ═══════════════════════════════════════════════════════════════════════════
-- Established 2026-08-17 by reading supabase_migrations.schema_migrations on
-- the live project. These same three DROP POLICY statements were applied on
-- 2026-07-11 as `restrict_public_bucket_listing` (self-labelled "018") and
-- rolled back the next day, 2026-07-12, by `restore_public_bucket_read_policies`.
-- The rollback migration states the cause in its own header:
--
--     "Dropping them broke uploads (Supabase's upload does INSERT ... RETURNING,
--      which needs a SELECT policy to read the new row back). Re-create them
--      exactly as they were so uploads work again. (The enumeration hardening
--      will be redone a safer way.)"
--
-- So the failure mode is UPLOADS, not reads. Everything the "WHY DROPPING THESE
-- IS SAFE" section below says about read paths is correct and beside the point:
-- reads on a public bucket really do bypass RLS. The write path does not. The
-- INSERT succeeds and then the RETURNING clause is denied, so the client sees
-- the upload fail.
--
-- Note what this file predicts as its own blast radius: "all audio playback
-- stops". That is the wrong failure. The one verification step that WOULD have
-- caught the real one is step 4, `node scripts/test-upload.mjs` — and that
-- script cannot authenticate, so it has never been able to pass. The check that
-- mattered is the check that does not run.
--
-- The hole itself is REAL and still open (re-verified live 2026-08-17: all three
-- `Public read mf-*` policies are still `SELECT TO public USING (bucket_id = …)`
-- with no other predicate, so the anon key still enumerates every bucket). It
-- needs the "safer way" the rollback promised and nobody ever built — most
-- likely a SELECT policy scoped so that `INSERT ... RETURNING` still reads back
-- the row just written while bulk enumeration is refused. That shape must be
-- established EMPIRICALLY, on a Supabase branch or a throwaway probe bucket,
-- not by reasoning. Reasoning is what produced this file.
--
-- Superseded-by: nothing yet. Kept only as the record of a refuted approach.
-- ═══════════════════════════════════════════════════════════════════════════
--
-- THE HOLE
-- Migrations 003 and 014 gave each bucket a SELECT policy on storage.objects
-- whose entire condition is `bucket_id = '<bucket>'`, granted to role `public`.
-- That is not "public read of objects" — object reads on a PUBLIC bucket never
-- consult RLS at all. What it actually grants is the ability to ENUMERATE the
-- bucket. Verified live with the anon key that ships in our own JS bundle:
--   POST /storage/v1/object/list/mf-audio   →   HTTP 200, rows returned
-- Object keys are `<projectId>/<timestamp>.<ext>`, and each maps directly to a
-- public object URL that serves without any check. So an unauthenticated
-- stranger can enumerate and download every unreleased mix, every piece of
-- artwork, and every finished video on the platform. Supabase's own security
-- advisor flags all three buckets (`public_bucket_allows_listing`).
--
-- WHY DROPPING THESE IS SAFE
-- Every read path in the app goes through `/storage/v1/object/public/...`,
-- which bypasses RLS because the buckets are public:
--   src/app/api/audio/[...path]/route.ts:20      (audio proxy)
--   src/app/api/artwork/[...path]/route.ts:24    (artwork proxy)
--   src/lib/download.ts:40                       (requires that exact prefix)
--   src/lib/supabase.ts:179, visualizer-store.ts:87, every getPublicUrl() site
-- Server-side reads, lists and deletes all use the service-role key, which
-- bypasses RLS entirely. There is NO client-side `.list()` anywhere in `src/`
-- or `ios/` — grepped before writing this. Nothing legitimate depends on these
-- policies.
--
-- WHAT THIS DOES NOT FIX
-- The INSERT policies from migration 009 still allow ANONYMOUS uploads into all
-- three buckets (`with check (bucket_id = ...)`, no auth predicate, 2 GB/file).
-- That is a separate change: scoping it `to authenticated` may break the ≤50 MB
-- signed-URL browser upload path depending on how Supabase validates signed
-- upload tokens, so it needs a real upload test, not a guess. Left open
-- deliberately rather than fixed blind.

-- NEUTRALISED 2026-08-17. Left in place, commented out, so that applying this
-- file is a no-op rather than a repeat of the 07-11 outage. Do not uncomment
-- without the empirical rehearsal described at the top.
-- drop policy if exists "Public read mf-audio"   on storage.objects;
-- drop policy if exists "Public read mf-artwork" on storage.objects;
-- drop policy if exists "Public read mf-video"   on storage.objects;

-- APPLY + VERIFY (HISTORICAL — step 4 is the step that never ran; see top)
--   1. Apply this file.
--   2. Confirm listing is dead (expect a permission error, not 200 with rows):
--        curl -s -X POST "$SUPABASE_URL/storage/v1/object/list/mf-audio" \
--          -H "apikey: $ANON_KEY" -H "Authorization: Bearer $ANON_KEY" \
--          -H 'Content-Type: application/json' -d '{"prefix":"","limit":5}'
--   3. Confirm playback still works (expect HTTP 206 + Content-Range):
--        curl -sI -H 'Range: bytes=0-1023' https://mixbase.app/api/audio/<known-key>
--   4. node scripts/test-upload.mjs https://mixbase-staging.up.railway.app
--
-- ROLLBACK — recreate any policy verbatim:
--   create policy "Public read mf-audio" on storage.objects
--     for select using (bucket_id = 'mf-audio');
--
-- NOTE ON APPLYING: staging and production share one Supabase project, so there
-- is no isolated environment to rehearse this in. The reasoning above is sound
-- and every call site was checked, but the blast radius if Supabase's
-- public-object semantics differ from the documented behaviour is "all audio
-- playback stops". Apply it deliberately, with step 3 ready to run.
